# Generated by Django 4.2.9 on 2024-01-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preke',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='nuotraukos', verbose_name='Nuotrauka'),
        ),
    ]
