# Generated by Django 4.2.9 on 2024-01-21 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eparduotuve', '0003_alter_atsiliepimas_options_atsiliepimas_vertintojas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilis',
            fields=[
                ('vardas', models.CharField(max_length=50, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=50, verbose_name='Pavardė')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus vartotojo ID.', primary_key=True, serialize=False)),
                ('kortele', models.CharField(blank=True, max_length=13, null=True, verbose_name='Banko kortelės numeris')),
                ('status', models.CharField(blank=True, choices=[('k', 'Koretele'), ('g', 'Grynaisiais'), ('p', 'Pavedimu'), ('d', 'Dovanų čekis')], default='k', help_text='Apmokėjimo būdo pasirinkimas', max_length=1, verbose_name='Apmokėjimas')),
                ('vartotojas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilis',
                'verbose_name_plural': 'Profiliai',
            },
        ),
    ]
