# Generated by Django 4.2.9 on 2024-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0005_alter_profilis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilis',
            name='adresas',
            field=models.CharField(blank=True, max_length=30, verbose_name='Adresas'),
        ),
    ]
