# Generated by Django 4.2.9 on 2024-01-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0007_remove_krepselis_pristatymo_budas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilis',
            old_name='id',
            new_name='u_id',
        ),
        migrations.RemoveField(
            model_name='krepselis',
            name='profilio_unikalus_id',
        ),
        migrations.AddField(
            model_name='krepselis',
            name='Profilis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uuid', to='eparduotuve.profilis'),
        ),
    ]
