# Generated by Django 4.2.9 on 2024-01-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eparduotuve', '0008_rename_id_profilis_u_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krepselis',
            name='Profilis',
        ),
        migrations.AddField(
            model_name='krepselis',
            name='vartotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
