# Generated by Django 4.2.9 on 2024-01-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0009_remove_krepselis_profilis_krepselis_vartotojas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krepselis',
            options={},
        ),
    ]
