# Generated by Django 4.2.9 on 2024-01-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0010_alter_krepselis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krepselioeilutes',
            name='krepselis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='krepselis', to='eparduotuve.krepselis', verbose_name='Krepšelio numeris'),
        ),
    ]
