# Generated by Django 4.2.9 on 2024-01-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0011_alter_krepselioeilutes_krepselis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krepselioeilutes',
            name='krepselis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eparduotuve.krepselis', verbose_name='Krepšelio numeris'),
        ),
    ]
