# Generated by Django 4.2.9 on 2024-01-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eparduotuve', '0014_remove_krepselioeilutes_vartotojas_preke_aprasymas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krepselis',
            options={'verbose_name': 'Krepšelis', 'verbose_name_plural': 'Krepšeliai'},
        ),
    ]
